---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-radarr
  labels:
    type: downloads-radarr
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  iscsi:
     targetPortal: 10.0.0.11:3260
     iqn: iqn.2000-01.com.synology:crypteia.default-target.9ae28f60be2
     lun: 3
     fsType: 'ext4'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-radarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: downloads-radarr
---
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-sonarr
  labels:
    type: downloads-sonarr
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  iscsi:
     targetPortal: 10.0.0.11:3260
     iqn: iqn.2000-01.com.synology:crypteia.default-target.9ae28f60be2
     lun: 4
     fsType: 'ext4'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-sonarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: downloads-sonarr
---
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-overseerr
  labels:
    type: downloads-overseerr
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  iscsi:
     targetPortal: 10.0.0.11:3260
     iqn: iqn.2000-01.com.synology:crypteia.default-target.9ae28f60be2
     lun: 7
     fsType: 'ext4'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-overseerr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      type: downloads-overseerr
---