apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - metrics-server/deployment.yaml
  - reloader/deployment.yaml
  - node-feature-discovery/deployment.yaml
  - intel-device-operator/deployment.yaml
 # - intel-gpu-plugin/deployment.yaml
